# Development stage
FROM node:22-alpine as dev

# Define working directory in container
# WORKDIR /app

# # Copy package.json and package-lock.json to container
# COPY package*.json ./
# RUN  npm install

# # Copy all files to container
# COPY . .

# CMD ["npx", "nodemon"]


# # Production stage
# FROM node:22-alpine as prod

# # Define working directory in container
# WORKDIR /app

# # Copy package.json and package-lock.json to container
# COPY backend/package.json ./
# RUN npm install

# # Copy all files to container
# COPY backend/ .

# # Start the app in production
# CMD ["node", "index.js"]

# ---- Base stage ----
FROM node:18-alpine AS base

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# ---- Development stage ----
FROM base AS dev

ENV NODE_ENV=development

CMD ["npm", "run", "dev"]

# ---- Production stage (optional) ----
FROM base AS prod

ENV NODE_ENV=production

RUN npm ci --only=production

CMD ["node", "app.js"]

